version: "3"
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testing
      MYSQL_ROOT_PASSWORD: "zxcvbnm"

  laravel-app:
    build:
      context: .
      dockerfile: ./newsbackend/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mysql
    volumes:
      - ./newsbackend:/var/www/html

  react-app:
    build:
      context: .
      dockerfile: ./newsaggregatorwebsite/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - laravel-app
    volumes:
      - ./newsaggregatorwebsite:/app